Repository dwyl/phoenix-liveview-todo-list-tutorial, pull requests merged in 2022-07, with the labels that each got.

#38 PR: Edit todo list item
  README.md
  lib/live_view_todo_web/live/page_live.ex
  lib/live_view_todo_web/live/page_live.html.heex
  test/live_view_todo_web/live/page_live_test.exs
Labels: awaiting-review

#40 Focus edited items
  README.md
  assets/js/app.js
  lib/live_view_todo_web/live/page_live.html.heex
Labels: awaiting-review

#42 update readme links
  README.md
Labels: enhancement, help wanted, chore

#47 Add Table of Contents
  .gitignore
  README.md
Labels: enhancement, chore, T5m, awaiting-review
